services:
  axonserver:
    image: 'axoniq/axonserver:latest'
    environment:
      - 'AXONIQ_AXONSERVER_STANDALONE=TRUE'
    ports:
      - '8024:8024'
      - '8124:8124'

  airbnb-postgres-db:
    image: postgres:latest
    container_name: airbnb-postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Hop2005@
      POSTGRES_DB: airbnb_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  airbnb-network:
    driver: bridge